language: go

go:
  - "1.11"
  - "1.12"
  - stable

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - GO111MODULE=on go mod vendor

script:
  - make test
  - $GOPATH/bin/overalls -project=github.com/hellofresh/kandalf -covermode=count
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile; fi

